name: ci

on: push

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Run test script
        uses: cypress-io/github-action@v4
      - name: Install dependencies
        run: npm install
      - name: Run test
        run: npm test
